### ISSUE TITLE
handshake -> reset

### ISSUE THREAD

**Issue by roburb** [mightymos/OnbrightFlasher#6]
Hi all,
I would ask for help, how to continue.
I am following the flashing guide by example, all up to step handshake works
OnbrightFlasher is uploaded
after send to serial console handshake and reconnecting power, there is listed:

```
handshake
State changing to handshake
cycle power to target (start with power off and then turn on)

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v00045af0
~ld
��n�r��n|�l�l`bbrl�nB�nl`�rl�l�� 
Ready.
Date: Nov 13 2024 Time: 07:34:44
Entering [idle] state.
Type [handshake] to attempt connection to target.
Type [idle] and then [handshake] to retry from the beginning
```

I don't know what I shall do now.
Could some help me please?

**Comment by mightymos** [comment]
After you type in "handshake", you then have to apply power to the target microcontroller.
How are you supplying 3.3V to the microcontroller?

**Comment by roburb** [comment]
I send "handshake" on serial console and the apply power. I use 3.3V from pin of Wemos D1.

**Comment by mightymos** [comment]
> I send "handshake" on serial console and the apply power. I use 3.3V from pin of Wemos D1.

If you take 3.3V from the pin of the Wemos it could be triggering the brown out detector which resets the Wemos.
You need to provide power from another source like a bench top supply or a usb to serial converter with 3.3V output.

**Comment by roburb** [comment]
Thank you,
I have used 3.3V power from usb to serial convert and everything works :-)
